
export enum Difficulty {
  BEGINNER = 'Beginner',
  INTERMEDIATE = 'Intermediate',
  ADVANCED = 'Advanced'
}

export interface Resource {
  id: string;
  type: 'video' | 'reading' | 'book' | 'course' | 'youtube' | 'pdf';
  category: 'free' | 'paid';
  title: string;
  provider: string;
  url: string;
  duration?: string;
}

export interface RoadmapNode {
  id: string;
  title: string;
  description: string;
  status: 'locked' | 'unlocked' | 'completed';
  resources: Resource[];
  topics: string[];
  practicePrompt?: string;
  practiceCode?: string;
  proTips?: string;
}

export interface CareerPath {
  id: string;
  title: string;
  description: string;
  starterGuide?: string;
  nodes: RoadmapNode[];
}

export interface ProjectPhase {
  id: string;
  title: string;
  tasks: string[];
  details: string;
}

export interface Project {
  id: string;
  tier: 1 | 2 | 3;
  title: string;
  description: string;
  phases: ProjectPhase[];
  tech: string[];
}

export interface Article {
  id: string;
  title: string;
  summary: string;
  tag: string;
  date: string;
  url: string;
  source?: string;
}

export interface Job {
  id: string;
  company: string;
  role: string;
  location: string;
  requiredNodes: string[];
  salary: string;
  category: 'job' | 'internship';
  description: string;
  eligibility: string[];
  applyUrl: string;
  experience?: string;
  skills?: string[];
}

export interface QuizQuestion {
  id: string;
  question: string;
  options: string[];
  correctAnswer: string;
}

export interface ProblemSet {
  id: string;
  title: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  description: string;
  starterCode: string;
  testCases: string[];
}

export interface Application {
  id: string;
  jobId: string;
  status: 'To Apply' | 'Applied' | 'Interview' | 'Offer';
}

export interface Reminder {
  id: string;
  text: string;
  dueDate: string;
  completed: boolean;
  priority: 'low' | 'medium' | 'high';
}

/**
 * Interface representing a career path recommendation generated by AI.
 * This fixes the 'Module "./types" has no exported member "Recommendation"' error.
 */
export interface Recommendation {
  pathId: string;
  title: string;
  reason: string;
  matchScore: number;
  starterGuide: string;
  milestones: {
    title: string;
    description: string;
    topics: string[];
    proTips: string;
    resources: Resource[];
  }[];
}

export type ViewState = 'home' | 'onboarding' | 'dashboard' | 'roadmap' | 'editor' | 'projects' | 'news' | 'vault' | 'launchpad' | 'learning-lab';

export interface UserProfile {
  name: string;
  knownSkills: string[];
  interest: string;
  language: string;
  skillLevel: Difficulty;
  completedNodes: string[];
  applications: Application[];
  reminders: Reminder[];
  quizScores: { category: string; score: number; total: number }[];
  dynamicRoadmap?: RoadmapNode[];
  dynamicStarterGuide?: string;
}

export interface ChatMessage {
  role: 'user' | 'model';
  text: string;
}

export interface VirtualFile {
  id: string;
  name: string;
  content: string;
  language: string;
}
